### ISSUE TITLE
Link to "permissions" doc missing

### ISSUE THREAD

**Issue by drnic** [IBM-Bluemix-Docs/cloud-foundry#18]
https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-create-environment#prerequisites 

Second bullet "Ensure that you have the correct permissions" links to https://cloud.ibm.com/catalog/docs/cloud-foundry/permissions.html but that page is missing/404

**Comment by Lucsantosg** [comment]
Fixed. Thanks for noticing (should be life in a few minutes).
Sorry for the delay, i hadn't seen this issue.
